/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ninja.taskbook.model.network.thrift.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-05-19")
public class ThriftTaskInfo implements org.apache.thrift.TBase<ThriftTaskInfo, ThriftTaskInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftTaskInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftTaskInfo");

  private static final org.apache.thrift.protocol.TField TASK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("taskId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField GROUP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("groupId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField TASK_AUTHOR_FIELD_DESC = new org.apache.thrift.protocol.TField("taskAuthor", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TASK_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("taskName", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField TASK_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("taskContent", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField TASK_BEGINNING_FIELD_DESC = new org.apache.thrift.protocol.TField("taskBeginning", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField TASK_DEADLINE_FIELD_DESC = new org.apache.thrift.protocol.TField("taskDeadline", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField TASK_PROGRESS_FIELD_DESC = new org.apache.thrift.protocol.TField("taskProgress", org.apache.thrift.protocol.TType.DOUBLE, (short)8);
  private static final org.apache.thrift.protocol.TField USER_ROLE_FIELD_DESC = new org.apache.thrift.protocol.TField("userRole", org.apache.thrift.protocol.TType.I32, (short)9);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThriftTaskInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThriftTaskInfoTupleSchemeFactory());
  }

  public int taskId; // required
  public int groupId; // required
  public String taskAuthor; // required
  public String taskName; // required
  public String taskContent; // required
  public String taskBeginning; // required
  public String taskDeadline; // required
  public double taskProgress; // required
  public int userRole; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TASK_ID((short)1, "taskId"),
    GROUP_ID((short)2, "groupId"),
    TASK_AUTHOR((short)3, "taskAuthor"),
    TASK_NAME((short)4, "taskName"),
    TASK_CONTENT((short)5, "taskContent"),
    TASK_BEGINNING((short)6, "taskBeginning"),
    TASK_DEADLINE((short)7, "taskDeadline"),
    TASK_PROGRESS((short)8, "taskProgress"),
    USER_ROLE((short)9, "userRole");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TASK_ID
          return TASK_ID;
        case 2: // GROUP_ID
          return GROUP_ID;
        case 3: // TASK_AUTHOR
          return TASK_AUTHOR;
        case 4: // TASK_NAME
          return TASK_NAME;
        case 5: // TASK_CONTENT
          return TASK_CONTENT;
        case 6: // TASK_BEGINNING
          return TASK_BEGINNING;
        case 7: // TASK_DEADLINE
          return TASK_DEADLINE;
        case 8: // TASK_PROGRESS
          return TASK_PROGRESS;
        case 9: // USER_ROLE
          return USER_ROLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TASKID_ISSET_ID = 0;
  private static final int __GROUPID_ISSET_ID = 1;
  private static final int __TASKPROGRESS_ISSET_ID = 2;
  private static final int __USERROLE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.USER_ROLE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TASK_ID, new org.apache.thrift.meta_data.FieldMetaData("taskId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.GROUP_ID, new org.apache.thrift.meta_data.FieldMetaData("groupId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TASK_AUTHOR, new org.apache.thrift.meta_data.FieldMetaData("taskAuthor", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TASK_NAME, new org.apache.thrift.meta_data.FieldMetaData("taskName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TASK_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("taskContent", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TASK_BEGINNING, new org.apache.thrift.meta_data.FieldMetaData("taskBeginning", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TASK_DEADLINE, new org.apache.thrift.meta_data.FieldMetaData("taskDeadline", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TASK_PROGRESS, new org.apache.thrift.meta_data.FieldMetaData("taskProgress", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.USER_ROLE, new org.apache.thrift.meta_data.FieldMetaData("userRole", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftTaskInfo.class, metaDataMap);
  }

  public ThriftTaskInfo() {
  }

  public ThriftTaskInfo(
    int taskId,
    int groupId,
    String taskAuthor,
    String taskName,
    String taskContent,
    String taskBeginning,
    String taskDeadline,
    double taskProgress)
  {
    this();
    this.taskId = taskId;
    setTaskIdIsSet(true);
    this.groupId = groupId;
    setGroupIdIsSet(true);
    this.taskAuthor = taskAuthor;
    this.taskName = taskName;
    this.taskContent = taskContent;
    this.taskBeginning = taskBeginning;
    this.taskDeadline = taskDeadline;
    this.taskProgress = taskProgress;
    setTaskProgressIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftTaskInfo(ThriftTaskInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.taskId = other.taskId;
    this.groupId = other.groupId;
    if (other.isSetTaskAuthor()) {
      this.taskAuthor = other.taskAuthor;
    }
    if (other.isSetTaskName()) {
      this.taskName = other.taskName;
    }
    if (other.isSetTaskContent()) {
      this.taskContent = other.taskContent;
    }
    if (other.isSetTaskBeginning()) {
      this.taskBeginning = other.taskBeginning;
    }
    if (other.isSetTaskDeadline()) {
      this.taskDeadline = other.taskDeadline;
    }
    this.taskProgress = other.taskProgress;
    this.userRole = other.userRole;
  }

  public ThriftTaskInfo deepCopy() {
    return new ThriftTaskInfo(this);
  }

  @Override
  public void clear() {
    setTaskIdIsSet(false);
    this.taskId = 0;
    setGroupIdIsSet(false);
    this.groupId = 0;
    this.taskAuthor = null;
    this.taskName = null;
    this.taskContent = null;
    this.taskBeginning = null;
    this.taskDeadline = null;
    setTaskProgressIsSet(false);
    this.taskProgress = 0.0;
    setUserRoleIsSet(false);
    this.userRole = 0;
  }

  public int getTaskId() {
    return this.taskId;
  }

  public ThriftTaskInfo setTaskId(int taskId) {
    this.taskId = taskId;
    setTaskIdIsSet(true);
    return this;
  }

  public void unsetTaskId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  /** Returns true if field taskId is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskId() {
    return EncodingUtils.testBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  public void setTaskIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TASKID_ISSET_ID, value);
  }

  public int getGroupId() {
    return this.groupId;
  }

  public ThriftTaskInfo setGroupId(int groupId) {
    this.groupId = groupId;
    setGroupIdIsSet(true);
    return this;
  }

  public void unsetGroupId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __GROUPID_ISSET_ID);
  }

  /** Returns true if field groupId is set (has been assigned a value) and false otherwise */
  public boolean isSetGroupId() {
    return EncodingUtils.testBit(__isset_bitfield, __GROUPID_ISSET_ID);
  }

  public void setGroupIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __GROUPID_ISSET_ID, value);
  }

  public String getTaskAuthor() {
    return this.taskAuthor;
  }

  public ThriftTaskInfo setTaskAuthor(String taskAuthor) {
    this.taskAuthor = taskAuthor;
    return this;
  }

  public void unsetTaskAuthor() {
    this.taskAuthor = null;
  }

  /** Returns true if field taskAuthor is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskAuthor() {
    return this.taskAuthor != null;
  }

  public void setTaskAuthorIsSet(boolean value) {
    if (!value) {
      this.taskAuthor = null;
    }
  }

  public String getTaskName() {
    return this.taskName;
  }

  public ThriftTaskInfo setTaskName(String taskName) {
    this.taskName = taskName;
    return this;
  }

  public void unsetTaskName() {
    this.taskName = null;
  }

  /** Returns true if field taskName is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskName() {
    return this.taskName != null;
  }

  public void setTaskNameIsSet(boolean value) {
    if (!value) {
      this.taskName = null;
    }
  }

  public String getTaskContent() {
    return this.taskContent;
  }

  public ThriftTaskInfo setTaskContent(String taskContent) {
    this.taskContent = taskContent;
    return this;
  }

  public void unsetTaskContent() {
    this.taskContent = null;
  }

  /** Returns true if field taskContent is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskContent() {
    return this.taskContent != null;
  }

  public void setTaskContentIsSet(boolean value) {
    if (!value) {
      this.taskContent = null;
    }
  }

  public String getTaskBeginning() {
    return this.taskBeginning;
  }

  public ThriftTaskInfo setTaskBeginning(String taskBeginning) {
    this.taskBeginning = taskBeginning;
    return this;
  }

  public void unsetTaskBeginning() {
    this.taskBeginning = null;
  }

  /** Returns true if field taskBeginning is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskBeginning() {
    return this.taskBeginning != null;
  }

  public void setTaskBeginningIsSet(boolean value) {
    if (!value) {
      this.taskBeginning = null;
    }
  }

  public String getTaskDeadline() {
    return this.taskDeadline;
  }

  public ThriftTaskInfo setTaskDeadline(String taskDeadline) {
    this.taskDeadline = taskDeadline;
    return this;
  }

  public void unsetTaskDeadline() {
    this.taskDeadline = null;
  }

  /** Returns true if field taskDeadline is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskDeadline() {
    return this.taskDeadline != null;
  }

  public void setTaskDeadlineIsSet(boolean value) {
    if (!value) {
      this.taskDeadline = null;
    }
  }

  public double getTaskProgress() {
    return this.taskProgress;
  }

  public ThriftTaskInfo setTaskProgress(double taskProgress) {
    this.taskProgress = taskProgress;
    setTaskProgressIsSet(true);
    return this;
  }

  public void unsetTaskProgress() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TASKPROGRESS_ISSET_ID);
  }

  /** Returns true if field taskProgress is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskProgress() {
    return EncodingUtils.testBit(__isset_bitfield, __TASKPROGRESS_ISSET_ID);
  }

  public void setTaskProgressIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TASKPROGRESS_ISSET_ID, value);
  }

  public int getUserRole() {
    return this.userRole;
  }

  public ThriftTaskInfo setUserRole(int userRole) {
    this.userRole = userRole;
    setUserRoleIsSet(true);
    return this;
  }

  public void unsetUserRole() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERROLE_ISSET_ID);
  }

  /** Returns true if field userRole is set (has been assigned a value) and false otherwise */
  public boolean isSetUserRole() {
    return EncodingUtils.testBit(__isset_bitfield, __USERROLE_ISSET_ID);
  }

  public void setUserRoleIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERROLE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TASK_ID:
      if (value == null) {
        unsetTaskId();
      } else {
        setTaskId((Integer)value);
      }
      break;

    case GROUP_ID:
      if (value == null) {
        unsetGroupId();
      } else {
        setGroupId((Integer)value);
      }
      break;

    case TASK_AUTHOR:
      if (value == null) {
        unsetTaskAuthor();
      } else {
        setTaskAuthor((String)value);
      }
      break;

    case TASK_NAME:
      if (value == null) {
        unsetTaskName();
      } else {
        setTaskName((String)value);
      }
      break;

    case TASK_CONTENT:
      if (value == null) {
        unsetTaskContent();
      } else {
        setTaskContent((String)value);
      }
      break;

    case TASK_BEGINNING:
      if (value == null) {
        unsetTaskBeginning();
      } else {
        setTaskBeginning((String)value);
      }
      break;

    case TASK_DEADLINE:
      if (value == null) {
        unsetTaskDeadline();
      } else {
        setTaskDeadline((String)value);
      }
      break;

    case TASK_PROGRESS:
      if (value == null) {
        unsetTaskProgress();
      } else {
        setTaskProgress((Double)value);
      }
      break;

    case USER_ROLE:
      if (value == null) {
        unsetUserRole();
      } else {
        setUserRole((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TASK_ID:
      return getTaskId();

    case GROUP_ID:
      return getGroupId();

    case TASK_AUTHOR:
      return getTaskAuthor();

    case TASK_NAME:
      return getTaskName();

    case TASK_CONTENT:
      return getTaskContent();

    case TASK_BEGINNING:
      return getTaskBeginning();

    case TASK_DEADLINE:
      return getTaskDeadline();

    case TASK_PROGRESS:
      return getTaskProgress();

    case USER_ROLE:
      return getUserRole();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TASK_ID:
      return isSetTaskId();
    case GROUP_ID:
      return isSetGroupId();
    case TASK_AUTHOR:
      return isSetTaskAuthor();
    case TASK_NAME:
      return isSetTaskName();
    case TASK_CONTENT:
      return isSetTaskContent();
    case TASK_BEGINNING:
      return isSetTaskBeginning();
    case TASK_DEADLINE:
      return isSetTaskDeadline();
    case TASK_PROGRESS:
      return isSetTaskProgress();
    case USER_ROLE:
      return isSetUserRole();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftTaskInfo)
      return this.equals((ThriftTaskInfo)that);
    return false;
  }

  public boolean equals(ThriftTaskInfo that) {
    if (that == null)
      return false;

    boolean this_present_taskId = true;
    boolean that_present_taskId = true;
    if (this_present_taskId || that_present_taskId) {
      if (!(this_present_taskId && that_present_taskId))
        return false;
      if (this.taskId != that.taskId)
        return false;
    }

    boolean this_present_groupId = true;
    boolean that_present_groupId = true;
    if (this_present_groupId || that_present_groupId) {
      if (!(this_present_groupId && that_present_groupId))
        return false;
      if (this.groupId != that.groupId)
        return false;
    }

    boolean this_present_taskAuthor = true && this.isSetTaskAuthor();
    boolean that_present_taskAuthor = true && that.isSetTaskAuthor();
    if (this_present_taskAuthor || that_present_taskAuthor) {
      if (!(this_present_taskAuthor && that_present_taskAuthor))
        return false;
      if (!this.taskAuthor.equals(that.taskAuthor))
        return false;
    }

    boolean this_present_taskName = true && this.isSetTaskName();
    boolean that_present_taskName = true && that.isSetTaskName();
    if (this_present_taskName || that_present_taskName) {
      if (!(this_present_taskName && that_present_taskName))
        return false;
      if (!this.taskName.equals(that.taskName))
        return false;
    }

    boolean this_present_taskContent = true && this.isSetTaskContent();
    boolean that_present_taskContent = true && that.isSetTaskContent();
    if (this_present_taskContent || that_present_taskContent) {
      if (!(this_present_taskContent && that_present_taskContent))
        return false;
      if (!this.taskContent.equals(that.taskContent))
        return false;
    }

    boolean this_present_taskBeginning = true && this.isSetTaskBeginning();
    boolean that_present_taskBeginning = true && that.isSetTaskBeginning();
    if (this_present_taskBeginning || that_present_taskBeginning) {
      if (!(this_present_taskBeginning && that_present_taskBeginning))
        return false;
      if (!this.taskBeginning.equals(that.taskBeginning))
        return false;
    }

    boolean this_present_taskDeadline = true && this.isSetTaskDeadline();
    boolean that_present_taskDeadline = true && that.isSetTaskDeadline();
    if (this_present_taskDeadline || that_present_taskDeadline) {
      if (!(this_present_taskDeadline && that_present_taskDeadline))
        return false;
      if (!this.taskDeadline.equals(that.taskDeadline))
        return false;
    }

    boolean this_present_taskProgress = true;
    boolean that_present_taskProgress = true;
    if (this_present_taskProgress || that_present_taskProgress) {
      if (!(this_present_taskProgress && that_present_taskProgress))
        return false;
      if (this.taskProgress != that.taskProgress)
        return false;
    }

    boolean this_present_userRole = true && this.isSetUserRole();
    boolean that_present_userRole = true && that.isSetUserRole();
    if (this_present_userRole || that_present_userRole) {
      if (!(this_present_userRole && that_present_userRole))
        return false;
      if (this.userRole != that.userRole)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_taskId = true;
    list.add(present_taskId);
    if (present_taskId)
      list.add(taskId);

    boolean present_groupId = true;
    list.add(present_groupId);
    if (present_groupId)
      list.add(groupId);

    boolean present_taskAuthor = true && (isSetTaskAuthor());
    list.add(present_taskAuthor);
    if (present_taskAuthor)
      list.add(taskAuthor);

    boolean present_taskName = true && (isSetTaskName());
    list.add(present_taskName);
    if (present_taskName)
      list.add(taskName);

    boolean present_taskContent = true && (isSetTaskContent());
    list.add(present_taskContent);
    if (present_taskContent)
      list.add(taskContent);

    boolean present_taskBeginning = true && (isSetTaskBeginning());
    list.add(present_taskBeginning);
    if (present_taskBeginning)
      list.add(taskBeginning);

    boolean present_taskDeadline = true && (isSetTaskDeadline());
    list.add(present_taskDeadline);
    if (present_taskDeadline)
      list.add(taskDeadline);

    boolean present_taskProgress = true;
    list.add(present_taskProgress);
    if (present_taskProgress)
      list.add(taskProgress);

    boolean present_userRole = true && (isSetUserRole());
    list.add(present_userRole);
    if (present_userRole)
      list.add(userRole);

    return list.hashCode();
  }

  @Override
  public int compareTo(ThriftTaskInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTaskId()).compareTo(other.isSetTaskId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskId, other.taskId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGroupId()).compareTo(other.isSetGroupId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGroupId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.groupId, other.groupId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskAuthor()).compareTo(other.isSetTaskAuthor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskAuthor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskAuthor, other.taskAuthor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskName()).compareTo(other.isSetTaskName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskName, other.taskName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskContent()).compareTo(other.isSetTaskContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskContent, other.taskContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskBeginning()).compareTo(other.isSetTaskBeginning());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskBeginning()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskBeginning, other.taskBeginning);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskDeadline()).compareTo(other.isSetTaskDeadline());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskDeadline()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskDeadline, other.taskDeadline);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskProgress()).compareTo(other.isSetTaskProgress());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskProgress()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskProgress, other.taskProgress);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserRole()).compareTo(other.isSetUserRole());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserRole()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userRole, other.userRole);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftTaskInfo(");
    boolean first = true;

    sb.append("taskId:");
    sb.append(this.taskId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("groupId:");
    sb.append(this.groupId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskAuthor:");
    if (this.taskAuthor == null) {
      sb.append("null");
    } else {
      sb.append(this.taskAuthor);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskName:");
    if (this.taskName == null) {
      sb.append("null");
    } else {
      sb.append(this.taskName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskContent:");
    if (this.taskContent == null) {
      sb.append("null");
    } else {
      sb.append(this.taskContent);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskBeginning:");
    if (this.taskBeginning == null) {
      sb.append("null");
    } else {
      sb.append(this.taskBeginning);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskDeadline:");
    if (this.taskDeadline == null) {
      sb.append("null");
    } else {
      sb.append(this.taskDeadline);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskProgress:");
    sb.append(this.taskProgress);
    first = false;
    if (isSetUserRole()) {
      if (!first) sb.append(", ");
      sb.append("userRole:");
      sb.append(this.userRole);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'taskId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'groupId' because it's a primitive and you chose the non-beans generator.
    if (taskAuthor == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskAuthor' was not present! Struct: " + toString());
    }
    if (taskName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskName' was not present! Struct: " + toString());
    }
    if (taskContent == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskContent' was not present! Struct: " + toString());
    }
    if (taskBeginning == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskBeginning' was not present! Struct: " + toString());
    }
    if (taskDeadline == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskDeadline' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'taskProgress' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftTaskInfoStandardSchemeFactory implements SchemeFactory {
    public ThriftTaskInfoStandardScheme getScheme() {
      return new ThriftTaskInfoStandardScheme();
    }
  }

  private static class ThriftTaskInfoStandardScheme extends StandardScheme<ThriftTaskInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftTaskInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TASK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.taskId = iprot.readI32();
              struct.setTaskIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // GROUP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.groupId = iprot.readI32();
              struct.setGroupIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TASK_AUTHOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskAuthor = iprot.readString();
              struct.setTaskAuthorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TASK_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskName = iprot.readString();
              struct.setTaskNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TASK_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskContent = iprot.readString();
              struct.setTaskContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TASK_BEGINNING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskBeginning = iprot.readString();
              struct.setTaskBeginningIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TASK_DEADLINE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskDeadline = iprot.readString();
              struct.setTaskDeadlineIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // TASK_PROGRESS
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.taskProgress = iprot.readDouble();
              struct.setTaskProgressIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // USER_ROLE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userRole = iprot.readI32();
              struct.setUserRoleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTaskId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetGroupId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'groupId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTaskProgress()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskProgress' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftTaskInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TASK_ID_FIELD_DESC);
      oprot.writeI32(struct.taskId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(GROUP_ID_FIELD_DESC);
      oprot.writeI32(struct.groupId);
      oprot.writeFieldEnd();
      if (struct.taskAuthor != null) {
        oprot.writeFieldBegin(TASK_AUTHOR_FIELD_DESC);
        oprot.writeString(struct.taskAuthor);
        oprot.writeFieldEnd();
      }
      if (struct.taskName != null) {
        oprot.writeFieldBegin(TASK_NAME_FIELD_DESC);
        oprot.writeString(struct.taskName);
        oprot.writeFieldEnd();
      }
      if (struct.taskContent != null) {
        oprot.writeFieldBegin(TASK_CONTENT_FIELD_DESC);
        oprot.writeString(struct.taskContent);
        oprot.writeFieldEnd();
      }
      if (struct.taskBeginning != null) {
        oprot.writeFieldBegin(TASK_BEGINNING_FIELD_DESC);
        oprot.writeString(struct.taskBeginning);
        oprot.writeFieldEnd();
      }
      if (struct.taskDeadline != null) {
        oprot.writeFieldBegin(TASK_DEADLINE_FIELD_DESC);
        oprot.writeString(struct.taskDeadline);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TASK_PROGRESS_FIELD_DESC);
      oprot.writeDouble(struct.taskProgress);
      oprot.writeFieldEnd();
      if (struct.isSetUserRole()) {
        oprot.writeFieldBegin(USER_ROLE_FIELD_DESC);
        oprot.writeI32(struct.userRole);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftTaskInfoTupleSchemeFactory implements SchemeFactory {
    public ThriftTaskInfoTupleScheme getScheme() {
      return new ThriftTaskInfoTupleScheme();
    }
  }

  private static class ThriftTaskInfoTupleScheme extends TupleScheme<ThriftTaskInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftTaskInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.taskId);
      oprot.writeI32(struct.groupId);
      oprot.writeString(struct.taskAuthor);
      oprot.writeString(struct.taskName);
      oprot.writeString(struct.taskContent);
      oprot.writeString(struct.taskBeginning);
      oprot.writeString(struct.taskDeadline);
      oprot.writeDouble(struct.taskProgress);
      BitSet optionals = new BitSet();
      if (struct.isSetUserRole()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetUserRole()) {
        oprot.writeI32(struct.userRole);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftTaskInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.taskId = iprot.readI32();
      struct.setTaskIdIsSet(true);
      struct.groupId = iprot.readI32();
      struct.setGroupIdIsSet(true);
      struct.taskAuthor = iprot.readString();
      struct.setTaskAuthorIsSet(true);
      struct.taskName = iprot.readString();
      struct.setTaskNameIsSet(true);
      struct.taskContent = iprot.readString();
      struct.setTaskContentIsSet(true);
      struct.taskBeginning = iprot.readString();
      struct.setTaskBeginningIsSet(true);
      struct.taskDeadline = iprot.readString();
      struct.setTaskDeadlineIsSet(true);
      struct.taskProgress = iprot.readDouble();
      struct.setTaskProgressIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.userRole = iprot.readI32();
        struct.setUserRoleIsSet(true);
      }
    }
  }

}

